# Generated by Django 3.2.6 on 2021-08-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='column_fk',
        ),
        migrations.AddField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('phone', 'phone number'), ('full_name', 'full name'), ('integer', 'integer')], default='phone', max_length=12),
        ),
        migrations.DeleteModel(
            name='FullNameType',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
