# Generated by Django 3.2.6 on 2021-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dataset_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='dataset',
            new_name='schema',
        ),
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
