# Generated by Django 3.2.6 on 2021-08-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210814_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='specific_range',
            field=models.JSONField(default='{}'),
        ),
    ]
