# Generated by Django 3.2.6 on 2021-08-14 13:54

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_column_specific_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='specific_range',
            field=models.JSONField(default=app.models.default_dict),
        ),
    ]
