# Generated by Django 3.2.6 on 2021-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_column_separator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='separator',
        ),
        migrations.AddField(
            model_name='schema',
            name='separator',
            field=models.CharField(choices=[('comma', 'Comma (,)'), ('semicolon', 'semicolon (;)'), ('pipe', 'pipe (|)')], default='comma', max_length=12),
        ),
    ]
