# Generated by Django 3.2.6 on 2021-08-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210814_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('phone', 'phone number'), ('full_name', 'full name'), ('integer', 'integer'), ('email', 'email'), ('job', 'job'), ('address', 'address')], default='phone', max_length=12),
        ),
    ]
