# Generated by Django 3.2.6 on 2021-08-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_schema_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'semicolon (;)'), ('|', 'pipe (|)')], default=',', max_length=12),
        ),
    ]
